const mainTypes = {
    SET_TITLE: 'SET_TITLE',
    SET_SYSTEM_INFO: 'SET_SYSTEM_INFO',
    SET_PAGE_LINK: 'SET_PAGE_LINK',
    LOADING: 'LOADING',
    AUTH_LOADING: 'AUTH_LOADING',
    SET_PAGE_SIZE: 'SET_PAGE_SIZE',
    SHOW_RIGHT_SIDER: 'SHOW_RIGHT_SIDER'
}

export default mainTypes;