const tfaTypes = {
    GET_PIN_CODE: 'GET_PIN_CODE',
    VERIFY_PIN_CODE: 'VERIFY_PIN_CODE',
    VERIFY_TOKEN: 'VERIFY_TOKEN',
    GET_BACKUP_CODES: 'GET_BACKUP_CODES',
    SEND_DISABLE_PIN: 'SEND_DISABLE_PIN',
    DISABLE_GOOGLE_AUTH: 'DISABLE_GOOGLE_AUTH',
}

export default tfaTypes