const userTypes = {
    USER_AUTH: 'USER_AUTH',
    USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
    USER_AUTH_FAILURE: 'USER_AUTH_FAILURE',
    GET_FEATURES: 'GET_FEATURES',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGIN: 'USER_LOGIN',
    USER_REGISTER: 'USER_REGISTER',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RECOVERY_PASSWORD: 'RECOVERY_PASSWORD',
    ACTIVATION_FIRST_STEP: 'ACTIVATION_FIRST_STEP',
    ACTIVATION_SECOND_STEP: 'ACTIVATION_SECOND_STEP',
    FINISH_ACTIVATION: 'FINISH_ACTIVATION',
    GET_POLICIES: 'GET_POLICIES',
    SOCIAL_CALLBACK: 'SOCIAL_CALLBACK',
    SOCIAL_LINK: 'SOCIAL_LINK',
    DISCONNECT_SOCIAL_ACCOUNT: 'DISCONNECT_SOCIAL_ACCOUNT',
    NEW_LICENSE: 'NEW_LICENSE',
    ACTIVATE_LICENSE: 'ACTIVATE_LICENSE',
}

export default userTypes;