const userTypes = {
    USER_AUTH: 'USER_AUTH',
    USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
    USER_AUTH_FAILURE: 'USER_AUTH_FAILURE',
    GET_FEATURES: 'GET_FEATURES',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGIN: 'USER_LOGIN',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RECOVERY_PASSWORD: 'RECOVERY_PASSWORD',
}

export default userTypes;