const usersTypes = {
    GET_USERS: 'GET_USERS',
    GET_USER: 'GET_USER',
    SET_USER: 'SET_USER',
    UPDATE_USER: 'UPDATE_USER',
    CHANGE_USER_PASSWORD: 'CHANGE_USER_PASSWORD',
    UPDATE_OPERATION_STATUS: 'UPDATE_OPERATION_STATUS',

    GET_GROUPS: 'GET_GROUPS',
    GET_EVENTS: 'GET_EVENTS',
    GET_SOCIALS: 'GET_SOCIALS',
    GET_GOOGLE_AUTHENTICATOR_VALUE: 'GET_GOOGLE_AUTHENTICATOR_VALUE',
    GET_SOCIALS_BY_USER: 'GET_SOCIALS_BY_USER',
}

export default usersTypes;